#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Thu Apr 23 10:07:04 GMT 2026
android.dependency.useConstraints=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.nonTransitiveRClass=true
android.r8.strictFullModeForKeepRules=false
android.uniquePackageNames=false
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8
systemProp.file.encoding=UTF-8
systemProp.sun.jnu.encoding=UTF-8
systemProp.user.country=US
systemProp.user.language=en
